### ISSUE TITLE
get an error with Formit 4.2.1-pl (MODX 2.7.1-pl | AjaxUpload 1.5.5-pl2)

### ISSUE THREAD

**Issue by jolichter** [Jako/AjaxUpload#28]
Hi Jako, I get following in modx error log:

> (ERROR @ /www/htdocs/web111/modx/core/components/ajaxupload/model/ajaxupload/ajaxupload.class.php : 139) PHP warning: include_once(/www/htdocs/web111/modx/core/components/formit/model/fileuploader/fileuploader.class.php): failed to open stream: Datei oder Verzeichnis nicht gefunden
> (ERROR @ /www/htdocs/web111/modx/core/components/ajaxupload/model/ajaxupload/ajaxupload.class.php : 139) PHP warning: include_once(): Failed opening '/www/htdocs/web111/modx/core/components/formit/model/fileuploader/fileuploader.class.php' for inclusion (include_path='.:/usr/share/php:..')

I switched back to Formit 4.1.1-pl and get no error. Maybe you can fix it?

**Comment by Jako** [comment]
Thats a FormIt issue. Why the heck do they send the FormIt core_path into the hook options (without a prefix) since 4.1.2?

But you could change those lines by removing the `ajaxupload.` key prefix: https://github.com/Jako/AjaxUpload/blob/master/core/components/ajaxupload/elements/snippets/ajaxupload2formit.snippet.php#L36-L38

The same change should be done in the other snippets.

Could you tell me, wether this works?

Greetings
Jako

**Comment by jolichter** [comment]
Yes, you have right and it is a FormIt issue. I removed the key prefix in those 3 snippets: AjaxUpload, AjaxUpload2Formit and Formit2AjaxUpload.
Now it's working in Formit 4.1.2 without an error.
THANKS A LOT!

btw: What is better? Are you adjust your snippet AjaxUpload or it's better to ask Sterc to fix his snippet FormIt?

**Comment by Jako** [comment]
I have created a new version of AjaxUpload
